version: '3.8'

services:
  mongodb:
    image: mongo:jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - OPEN_WEATHER_API_KEY=a22034aed53ca5845e3c8af45d527d3a
      - MONGO_URI=mongodb://admin:password@localhost:27017/admin